name: Publish Packages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: macos-latest
    strategy:
      matrix:
        package:
          - dependeasy
          - flatinvoker-core
          - flatinvoker-ffi
          # - flatinvoker-react  # will fix later
          - flatinvoker-compiler
          - reaktor-core
          - reaktor-io
          - reaktor-ui
          - reaktor-auth
          - reaktor-media
          - reaktor-navigation
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build everything.
        run: ./gradlew build

      - name: Publish ${{ matrix.package }}
        env:
          USERNAME: shibasis0801
          TOKEN: ${{ secrets.TOKEN }}
        run: ./gradlew :${{ matrix.package }}:publish